### PR TITLE
Item Module + Save Module

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TaoBoyce** [comment]
so in order for someone to save a game, they would have to:
1. create the save
2. update the save
3. output the save
4. destroy the save

and to load they would have to:
1. create the save
2. input the save
3. go through the save struct themselves and assign the value of each game variable to whatever is in the save struct
4. destroy the save

**Comment by TaoBoyce** [comment]
Items Handler looks good from what I can tell

**Comment by navjandu** [comment]
Looks good to me

**Review by navjandu — APPROVED** [review]

**Comment by ghost** [comment]
> 4\. save

That's correct

**Review by TaoBoyce — APPROVED** [review]
then it seems good

**Pull request merged**
